### ISSUE TITLE
Example file system structure?

### ISSUE THREAD

**Issue by oxr463** [5paceToast/zpe#1]
What does a managed `~/Workspace` look like? An example generated via `tree` would be nice.

For example, I typically create a `repos` directory, and store all git source code there,

```terminal
tree -d -L 2 ~/
/home/oxr463/
├── other directories
├── repos
│   ├── aports
│   ├── gentoo # ebuild tree
│   └── etc...
```

**Comment by CosmicToast** [comment]
zpe does not manage your workspace, it works with whatever you already have in there.
you "add" projects by giving their already checked out path, which is recorded.

**Comment by oxr463** [comment]
Oh interesting! Thanks for the info, I might have to try this out.
